-- Training log (Processing → Final Training history) & per-epoch metrics.
-- Jalankan sekali di Supabase SQL Editor.

create table if not exists public.training_logs (
  id bigint generated by default as identity primary key,
  name text,
  algo text,
  date timestamptz,
  ratio text,
  dataset text,
  params jsonb default '{}'::jsonb,
  hasil jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

create index if not exists training_logs_created_at_idx
  on public.training_logs (created_at);

create table if not exists public.model_epoch_metrics (
  id bigint generated by default as identity primary key,
  model_id bigint not null references public.models (id) on delete cascade,
  epoch integer,
  accuracy double precision,
  precision double precision,
  recall double precision,
  f1_score double precision,
  loss double precision,
  roc_auc double precision,
  mcc double precision,
  confusion_matrix jsonb,
  confusion_labels jsonb,
  created_at timestamptz default now()
);

create index if not exists model_epoch_metrics_model_id_idx
  on public.model_epoch_metrics (model_id);

create index if not exists model_epoch_metrics_model_epoch_idx
  on public.model_epoch_metrics (model_id, epoch);
